# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is set to Dgraph.
  - job_name: "dgraph"

    # The metrics_path is set to '/debug/prometheus_metrics' than the default '/metrics'.
    metrics_path: "/debug/prometheus_metrics"
    # Scraping interval is set to 2 seconds.
    scrape_interval: "2s"

    static_configs:
    - targets:
      - localhost:6080 # For Dgraph zero, 6080 is the http endpoint exposing metrics.
      - localhost:8080 # For Dgraph alpha.
